#
# Configuration
#

language: cpp

dist: trusty
sudo: required

#
# Compilers
#
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-3.8
      - llvm-toolchain-trusty-3.9
      - llvm-toolchain-trusty-4.0
    packages:
      - clang-3.8
      - clang-3.9
      - clang-4.0
      - clang-tidy-4.0
      - clang-format-4.0
      - llvm-4.0
      - gcc-6
      - g++-6
      - nasm
      - doxygen

#
# Update Build Environment
#
# Currently GCC and CMake are out of date. We require:
# - GCC 5+
# - CMake 3.6+
#
before_install:

  #
  # Path
  #
  - export PATH="$HOME/bfprefix/bin:$PATH"

  #
  # CMake
  #
  - wget https://cmake.org/files/v3.8/cmake-3.8.0-Linux-x86_64.sh
  - chmod +x cmake-*-Linux-x86_64.sh
  - sudo ./cmake-*-Linux-x86_64.sh --prefix=/usr/local --exclude-subdir --skip-license

  #
  # GCC
  #
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 100
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 100

#
# Build Dependencies
#
before_script:
  - mkdir build
  - cd build

#
# Build Matrix
#
matrix:
  include:

  #
  # Doxygen
  #
  - os: linux
    env:
      - TEST="Doxygen"
    script:
      - cd ..
      - doxygen .doxygen.txt
      - |
        if [[ -s doxygen_warnings.txt ]]; then
          echo "You must fix doxygen before submitting a pull request"
          echo ""
          cat doxygen_warnings.txt
          exit -1
        fi

  #
  # Git Check
  #
  - os: linux
    env:
      - TEST="Git Check"
    script:
      - |
        if [[ -n $(git diff --check HEAD^) ]]; then
          echo "You must remove whitespace before submitting a pull request"
          echo ""
          git diff --check HEAD^
          exit -1
        fi

  #
  # Astyle Format
  #
  - os: linux
    env:
      - TEST="Astyle Format"
    script:
      - cmake ..
      - make install
      - make format
      - |
        if [[ -n $(git diff) ]]; then
          echo "You must run make format before submitting a pull request"
          echo ""
          git diff
          exit -1
        fi

  #
  # Clang Tidy
  #
  - os: linux
    env:
      - TEST="Clang Tidy"
    script:
      - |
        cmake \
          -DENABLE_TIDY=ON \
          ..
      - make install
      - make tidy

  #
  # Codecov
  #
  - os: linux
    env:
      - TEST="Codecov"
    script:
      - |
        cmake \
          -DENABLE_COVERAGE=ON \
          ..
      - make
      - make test
      - cd ..
      - bash <(curl -s https://codecov.io/bash)

  #
  # LLVM SanitizerCoverage
  #
  - os: linux
    env:
      - TEST="LLVM SanitizerCoverage"
    script:
      - |
        cmake \
          -DENABLE_COVERAGE_LLVM=ON \
          ..
      - make install
      - make llvm_coverage

  #
  # Google Address Sanitizer
  #
  - os: linux
    env:
      - TEST="Google Address Sanitizer"
    script:
      - |
        cmake \
          -DENABLE_DYNAMIC_ASAN=ON \
          ..
      - make
      - make test

  #
  # Google Undefined Sanitizer
  #
  - os: linux
    env:
      - TEST="Google Undefined Sanitizer"
    script:
      - |
        cmake \
          -DENABLE_DYNAMIC_USAN=ON \
          ..
      - make
      - make test

  #
  # Native Test
  #
  - os: linux
    env:
      - TEST="Native Test"
    script:
      - |
        cmake \
          -DENABLE_UNITTESTING=ON \
          ..
      - make install
      - make test
